### ISSUE TITLE
Closing tape drive UI causes server to crash

### ISSUE THREAD

**Issue by t3435ryt** [Doenerstyle/AsieLib#1]
Computronics tape drives crash when they are closed with the current version (0.5.1). This does not occur on the original mod's most recent version. Also apologies in advance if my report is badly formatted, this is my first time making an issue.
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/16/24 7:10 AM
Description: Ticking memory connection

java.lang.ClassCastException: pl.asie.computronics.tile.TileTapeDrive cannot be cast to pl.asie.lib.block.TileEntityInventory
	at pl.asie.lib.block.ContainerBase.func_75134_a(ContainerBase.java:35)
	at net.minecraft.entity.player.EntityPlayerMP.func_71128_l(EntityPlayerMP.java:796)
	at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:874)
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(SourceFile:20)
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pl.asie.lib.block.ContainerBase.func_75134_a(ContainerBase.java:35)
	at net.minecraft.entity.player.EntityPlayerMP.func_71128_l(EntityPlayerMP.java:796)
	at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:874)
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(SourceFile:20)
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@666855e3
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4771536576 bytes (4550 MB) / 6202327040 bytes (5915 MB) up to 16971202560 bytes (16185 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx18208m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.3.10} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.6.49-GTNH} [NotEnoughItems] (NotEnoughItems-2.6.49-GTNH.jar) 
	UCHIJAAAA	OpenComputers|Core{1.8.6} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	asielib{0.5.1} [asielib] (AsieLib-1.7.10-0.5.1.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.26} [BuildCraft] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.26} [BC Silicon] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.26} [BC Robotics] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.26} [BC Energy] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.26} [BC Transport] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.26} [BC Factory] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.26} [BC Builders] (buildcraft-7.1.26.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	OpenComputers{1.8.6} [OpenComputers] (OpenComputers-MC1.7.10-1.8.6+b0b022a-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	computronics{1.6.6} [Computronics] (Computronics-1.7.10-1.6.6.jar) 
	UCHIJAAAA	controlling{1.7.10-1.0.0.8} [Controlling] (Controlling-1.7.10-1.0.0.8.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (5091)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X5091.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.2.7} [JourneyMap] (journeymap-1.7.10-5.2.7-unlimited.jar) 
	UCHIJAAAA	journeymap_api_1.7.10{1.1.0} [Journey Map Api for 1.7.10] (JourneyMapQol_1.7.10-1.1.0.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.0-1.jar) 
	UCHIJAAAA	mcheli{1.7} [MC Helicopter Overdrive] (new-vehicles) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	weather2{v2.3.19} [Localized Weather & Storms] (weather2-1.7.10-2.3.20.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['orangered8321'/88476, l='New World', x=-171.82, y=69.00, z=248.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Doenerstyle** [comment]
Hello there @t3435ryt,
thank you for reporting this crash! It should be fixed in v0.5.2 which I've released on GitHub and Modrinth. :)

PS: Your report is formatted perfectly fine! :p
